// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOXVXv3uzZPyfX7jeMS7fXqidr0dyscxo',
    appId: '1:1040221399084:web:7f06def59481a62aa28989',
    messagingSenderId: '1040221399084',
    projectId: 'elysium-xr7aa',
    authDomain: 'elysium-xr7aa.firebaseapp.com',
    storageBucket: 'elysium-xr7aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwCrZ6fvO-W5qrp_m0RS2dYCifv4Ax5A',
    appId: '1:1040221399084:android:0046bc96be863ff3a28989',
    messagingSenderId: '1040221399084',
    projectId: 'elysium-xr7aa',
    storageBucket: 'elysium-xr7aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBtgcM21gwgtv6QWZtcOSURnjgDlj__Q',
    appId: '1:1040221399084:ios:9a5f03fc7622efbaa28989',
    messagingSenderId: '1040221399084',
    projectId: 'elysium-xr7aa',
    storageBucket: 'elysium-xr7aa.appspot.com',
    iosBundleId: 'com.example.elysium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBtgcM21gwgtv6QWZtcOSURnjgDlj__Q',
    appId: '1:1040221399084:ios:a0d7e12f8c9aaa6da28989',
    messagingSenderId: '1040221399084',
    projectId: 'elysium-xr7aa',
    storageBucket: 'elysium-xr7aa.appspot.com',
    iosBundleId: 'com.example.elysium.RunnerTests',
  );
}
